export const kLlmSessionGetSupportedGpuEngines = 'Llm:Session:GetSupportedGpuEngines'
export const kLlmSessionGetModelScore = 'Llm:Session:GetModelScore'
export const kLlmSessionDisposeSession = 'Llm:Session:DisposeSession'
export const kLlmSessionExecPromptSession = 'Llm:Session:ExecPromptSession'
export const kLlmSessionExecChatSession = 'Llm:Session:ExecChatSession'
export const kLlmSessionGetEmbeddingVectors = 'Llm:Session:GetEmbeddingVectors'
export const kLlmSessionCountPromptTokens = 'Llm:Session:CountPromptTokens'
