export const kGetInstalledModels = 'Management:GetInstalledModels'
export const kUninstallModel = 'Management:UninstallModel'
export const kUpdateNativeBinary = 'Management:UpdateNativeBinary'
export const kGetInfo = 'Management:GetInfo'
export const kGetSupportedGpuEngines = 'Management:GetSupportedGpuEngines'
export const kGetInflightInstallProgress = 'Management:GetInflightInstallProgress'
